version: "3.8"

services:
    speedtest:
        container_name: speedtest
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - influxdb
        env_file: .env
        depends_on:
            - influxdb
        links: 
            - influxdb
    
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana:/var/lib/grafana
        depends_on: 
            - influxdb
        links:
            - influxdb
    
    influxdb:
        container_name: influxdb
        image: influxdb:2.0-alpine
        environment: 
            DOCKER_INFLUXDB_INIT_USERNAME: speedtest
            DOCKER_INFLUXDB_INIT_PASSWORD: speedtest
            DOCKER_INFLUXDB_INIT_ORG: speedtest-org
            DOCKER_INFLUXDB_INIT_BUCKET:  speedtest-bckt
        ports:
            - 8086:8086
        volumes: 
            - influxdb2:/var/lib/influxdb2
volumes: 
    influxdb2:
    grafana: